version: "3"

tasks:
  default:
    cmds:
      - task: generate
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./v2/gen/go/sso --go_opt=paths=source_relative --go-grpc_out=./v2/gen/go/sso --go-grpc_opt=paths=source_relative